name: Build & Publish Docker Image

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: agnesmardh/ourwishes-backend:${{ github.sha }}


