name: Build & Publish Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
      - name: Push Specific Tag to Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/agnesmardh/ourwishes-backend:${{ github.sha }}
      - name: Push Latest Tag to Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/agnesmardh/ourwishes-backend:latest
