name: Build & Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
      - name: Push Specific Tag to Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/agnesmardh/ourwishes-backend:${{ github.sha }}
      - name: Push Latest Tag to Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/agnesmardh/ourwishes-backend:latest

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - name: Deploy backend docker container
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'secret': '${{ secrets.DEPLOY_WEBHOOK_SECRET  }}'}"
