name: Publish Site

on:
  push:
    branches: [ main ]

jobs:
  build:

    environment: github-pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2
      - name: Publish site
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: yarn install
      - run: yarn prettier --check .
      - run: yarn test
      - name: Build
        run: |
          yarn build
        env:
          REACT_APP_COGNITO_REGION: ${{ secrets.REACT_APP_COGNITO_REGION }}
          REACT_APP_COGNITO_USER_POOL_ID: ${{ secrets.REACT_APP_COGNITO_USER_POOL_ID }}
          REACT_APP_COGNITO_APP_CLIENT_ID: ${{ secrets.REACT_APP_COGNITO_APP_CLIENT_ID }}
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          target_branch: gh-pages
          build_dir: ./frontend/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
