name: Publish Site

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2
      - name: Publish site
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: yarn install
      - run: yarn prettier --check .
      - run: yarn test
      - run: yarn build
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          target_branch: gh-pages
          build_dir: ./frontend/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
